version: '2'

services:
  neo4j:
    image: neo4j:3.2.2
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j:/data
  redis:
    image: redis:3.2.9
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"